INSERT INTO role (role, active, created_at)
VALUES ('ROLE_USER', true, now()),
       ('ROLE_ADMIN', true, now()),
       ('ROLE_ANONYMOUS', true, now());

INSERT INTO categories (name, show, parent_id, created_at)
values ('Food & Drinks', true, null, now()),
       ('Shopping', true, null, now()),
       ('Housing', true, null, now()),
       ('Transportation', true, null, now()),
       ('Vehicle', true, null, now()),
       ('Life & Entertainment', true, null, now()),
       ('Communication, PC', true, null, now()),
       ('Financial expenses', true, null, now()),
       ('Income', true, null, now()),
       ('Others', true, null, now());


INSERT INTO categories (name, show, parent_id, created_at)
VALUES ('Bar', true, 1, now()),
       ('Cafe', true, 1, now()),
       ('Groceries', true, 1, now()),
       ('Restaurant', true, 1, now()),
       ('Fast-food', true, 1, now()),
       ('Clothes & shoes', true, 2, now()),
       ('Drug-store, chemist', true, 2, now()),
       ('Electronics, accessories', true, 2, now()),
       ('Free time', true, 2, now()),
       ('Gifts, joy', true, 2, now()),
       ('Health and beauty', true, 2, now()),
       ('Home, garden', true, 2, now()),
       ('Jewels, accessories', true, 2, now()),
       ('Kids', true, 2, now()),
       ('Pets, animals', true, 2, now()),
       ('Stationery, tools', true, 2, now()),
       ('Energy, utilities', true, 3, now()),
       ('Maintenance, repairs', true, 3, now()),
       ('Mortgage', true, 3, now()),
       ('Property insurance', true, 3, now()),
       ('Rent', true, 3, now()),
       ('Services', true, 3, now()),
       ('Business trips', true, 4, now()),
       ('Long distance', true, 4, now()),
       ('Public transport', true, 4, now()),
       ('Taxi', true, 4, now()),
       ('Fuel', true, 5, now()),
       ('Parking', true, 5, now()),
       ('Rentals', true, 5, now()),
       ('Vehicle insurance', true, 5, now()),
       ('Vehicle maintenance', true, 5, now()),
       ('Books, audio, subscriptions', true, 6, now()),
       ('Charity, gifts', true, 6, now()),
       ('Culture, sport events', true, 6, now()),
       ('Education, development', true, 6, now()),
       ('Health care, doctor', true, 6, now()),
       ('Hobbies', true, 6, now()),
       ('Holiday, trips, hotels', true, 6, now()),
       ('Life events', true, 6, now()),
       ('Lottery, gambling', true, 6, now()),
       ('Gym', true, 6, now()),
       ('TV, Streaming', true, 6, now()),
       ('Wellness, beauty', true, 6, now()),
       ('Internet', true, 7, now()),
       ('Phone, mobile phone', true, 7, now()),
       ('Postal services', true, 7, now()),
       ('Software, apps, games', true, 7, now()),
       ('Advisory', true, 8, now()),
       ('Charges, Fees', true, 8, now()),
       ('Child Support', true, 8, now()),
       ('Fines', true, 8, now()),
       ('Insurances', true, 8, now()),
       ('Loan, interests', true, 8, now()),
       ('Taxes', true, 8, now()),
       ('Checks, coupons', true, 9, now()),
       ('Dues & grants', true, 9, now()),
       ('Gifts', true, 9, now()),
       ('Interests, dividends', true, 9, now()),
       ('Lending, renting', true, 9, now()),
       ('Refunds (tax, purchase)', true, 9, now()),
       ('Rental income', true, 9, now()),
       ('Sale', true, 9, now()),
       ('Wage, invoices', true, 9, now()),
       ('Missing', true, 10, now());
